### PR TITLE
double max render distance to 64

### LINKED ISSUE #192: [Feature Request] 32+ Render Distance
Could you add ability to go past vanilla 32 chunk render distance like in OF ?
This is being rejected by sodium but sodium extra is "Features that shouldn't be in Sodium." so...
https://github.com/CaffeineMC/sodium-fabric/issues/178
(Some guy asked in FO server if some mod provided the option and i thought it was in the scope of sodium extra)

### PR DESCRIPTION
**Pull request by isXander**
closes #192

### CODE REVIEW

**Comment by DragonEggBedrockBreaking** [comment]
Have you tested this code btw?

**Comment by FlashyReese** [comment]
This PR is incomplete, there are many places where vanilla clamps down the render distance to `32` regardless if you just change the render distance to `64`. There are also many other places where the game is hardcoded to `32`. It is also missing an entry in the mixin config plugin.

I should have commented about this on the original issue. I'm fairly hesitant about trying to even implement this feature because it involves messing with TACS which is a dumpster fire itself.

Edit: This change makes more sense for Bobby.

**Comment by isXander** [comment]
For users of farsight, using Bobby is out of the question.

**Comment by offbeat-stuff** [comment]
This mod increase render distance to 128
https://github.com/RelativityMC/C2ME-fabric/tree/b7ed18cb5b26865d5aaea1b575bd60fef74ceb57/c2me-client-uncapvd/src/main/java/com/ishland/c2me/client/uncapvd/mixin

**Comment by isXander** [comment]
C2ME has custom chunk loading and things

**Comment by FlashyReese** [comment]
I'm closing this PR as it's for an outdated branch.

**Pull request closed without merging**
