### PR TITLE
Add breaks context.

### PR DESCRIPTION
**Pull request by Kichura**
+ Adds the breaks context to blacklist specific mods as they cause errors or were not designed to run with this mod, this can be modified in case it makes no sense.

### CODE REVIEW

**Comment by K0-RR** [comment]
Optifabric and canvas are already blacklisted in Sodium.

**Comment by Kichura** [comment]
> Optifabric and canvas are already blacklisted in Sodium.

i added those in to this mod aswell in case people think this was compatible with other renderers just in case for the extra idiot-proofing.

**Comment by DragonEggBedrockBreaking** [comment]
> > Optifabric and canvas are already blacklisted in Sodium.
> 
> i added those in to this mod aswell in case people think this was compatible with other renderers just in case for the extra idiot-proofing.

But that’s pointless since this mod depends on sodium, meaning that it will just say sodium not installed…

**Comment by Kichura** [comment]
> > > Optifabric and canvas are already blacklisted in Sodium.
> > 
> > 
> > i added those in to this mod aswell in case people think this was compatible with other renderers just in case for the extra idiot-proofing.
> 
> But that’s pointless since this mod depends on sodium, meaning that it will just say sodium not installed…

will remove then.

**Comment by Kichura** [comment]
Closing this as PR has become stale + not worth it.

**Pull request closed without merging**
