### PR TITLE
Add support for QuiltMC by adding a `quilt.mod.json`

### LINKED ISSUE #205: Mod doesn't work on Quilt
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.2

### Sodium Extra version.

0.4.4

### Sodium version.

0.4.1

### What happened?

when the game loads with this mod, it crashes instead of working fine

### Relevant log.

[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/8715793/latest.log)

### Additional information.

_No response_

### PR DESCRIPTION
**Pull request by theRookieCoder**
Fixes #205

### CODE REVIEW

**Comment by theRookieCoder** [comment]
Hmm so the mod loads (shows up in logs and mod menu, and prints in the initialiser show up) but none of the features are actually present. Very peculiar

**Comment by theRookieCoder** [comment]
~~Ah I think it's because of the bundled JARs which I didn't specify in the `quilt.mod.json`~~

**Comment by theRookieCoder** [comment]
That was a seperate problem, but even after fixing that the extra config options aren't there

**Comment by theRookieCoder** [comment]
I think this is much more complicated than a simply adding a `quilt.mod.json`, I have no idea what the problem is

**Comment by FlashyReese** [comment]
We need to depend on QSL for Quilt. Since I'm just bundling individual Fabric modules, it's going to panic.

**Comment by theRookieCoder** [comment]
> We need to depend on QSL for Quilt

That's not necessary, same as it's not necessary to use Fabric API in Fabric mods.

> it's going to panic

Well I tested it and afaik it doesn't panic, the problem is it doesn't load any mixins.

**Pull request closed without merging**
